<template>
  <Navbar />
  <router-view />
</template>

<script>
import Navbar from "@/components/Navbar";

export default {
  name: "App",
  components: {
    Navbar,
  },
};
</script>

<style lang="scss">
@import url("https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: "Ubuntu", sans-serif;
  color: #333;
}

.btn-primary,
.bg-primary {
  background-color: #8e64f3 !important;
  border-color: #8e64f3 !important;
}

.bg-primary-2 {
  background: #d3c3f8 !important;
}

.text-primary {
  color: #8e64f3 !important;
}

.table-primary {
  --bs-table-bg: #d3c3f8 !important;
}

.text-h1 {
  font-size: 20px;
}

.text-h2 {
  font-size: 16px;
}

.text-h3 {
  font-size: 12px !important;
}

.back-button {
  font-size: 14px;
}

.profile {
  display: flex;
  width: 30px;
  height: 30px;
  align-items: center;
  justify-content: center;
  background-color: #8e64f3;
  color: #fff;
  border-radius: 50%;
}

.pulsate-fwd {
  animation: pulsate-fwd 0.5s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-10-16 0:1:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-fwd
 * ----------------------------------------
 */
@keyframes pulsate-fwd {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
}
</style>
